---
- name: install Apache
  apt:
    name: apache2
    state: latest

- name: install Apache Modules
  apache2_module:
    state: present
    name: '{{ item }}'
  notify:
    - restart apache
  with_items:
    - rewrite
    - vhost_alias
    - headers
    - expires
    - filter
    - a2enmod
    - proxy
    - proxy_http
    - xml2enc

- name: Change default apache2.4 site
  template:
    src: 'vhost24.conf.tpl'
    dest: '/etc/apache2/sites-available/000-default.conf'
  notify:
    - restart apache
