---
prometheus_version:                 1.7.1
prometheus_node_exporter_version:   0.14.0
prometheus_alertmanager_version:    0.8.0
prometheus_user: 'prometheus'
prometheus_group: 'prometheus'
prometheus_platform_suffix: 'linux-amd64'
gosu_version: '1.10'

prometheus_install_path:         /opt/prometheus
prometheus_config_path:          /etc/prometheus
prometheus_rule_path:            '{{ prometheus_config_path }}/rules'
prometheus_file_sd_config_path:  '{{ prometheus_config_path }}/tgroups'
prometheus_db_path:              '/var/lib/prometheus'
prometheus_log_path:             '/var/log/prometheus'
prometheus_pid_path:             '/var/run/prometheus'
prometheus_alertmanager_db_path: '/var/lib/alertmanager'

#prometheus_alertmanager_tarball_url: 'https://github.com/prometheus/alertmanager/releases/download/v{{ prometheus_alertmanager_version }}/{{ prometheus_alertmanager_signature }}.tar.gz'
prometheus_download_path: '/tmp'
prometheus_workdir:       '{{ prometheus_download_path }}/prometheus_workdir'
