---
- name: set internal variables
  set_fact:
    prometheus_subdir: '{{ prometheus_install_path }}/prometheus-{{ prometheus_version }}.linux-amd64'

- name: set download url
  set_fact:
    prometheus_tarball_url: 'https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz'

- name: set daemon dir
  set_fact:
    prometheus_daemon_dir: '{{ prometheus_subdir }}'

- name: download and untar prometheus tarball
  unarchive:
    src: '{{ prometheus_tarball_url }}'
    dest: '{{ prometheus_install_path }}'
    copy: no

- name: set permissions, owner and group
  file:
    path: '{{ prometheus_install_path }}'
    state: directory
    owner: prometheus
    group: prometheus
    mode: 'go-w'
    recurse: yes

- name: mkdir for config and data
  file:
    path: '{{ item }}'
    state: directory
    owner: prometheus
    group: prometheus
    mode: 'u=rwx,g=rx,o='
  with_items:
    - '{{ prometheus_rule_path }}'
    - '{{ prometheus_file_sd_config_path }}'
    - '{{ prometheus_db_path }}'

- name: set prometheus variables
  copy:
    src: 'files/etc-default-prometheus'
    dest: '/etc/default/prometheus'

- name: copy INIT script to server
  template:
    src: 'prometheus.sh.j2'
    dest: '/etc/init.d/prometheus'
    mode: 'a+x'

- name: set INIT status
  service:
    name: prometheus
    enabled: yes

- name: copy prometheus main config file
  template:
    src: 'prometheus.yml.j2'
    dest: '{{ prometheus_config_path }}/prometheus.yml'
    validate: '{{ prometheus_daemon_dir }}/promtool check-config %s'
  notify:
    - reload prometheus
